# Path to your oh-my-zsh installation.
export ZSH="/home/daniel/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration ==========================================================

## Specific software configs
### This prevents crash when Ctrl+s
stty -ixon

### pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

## Environment variables
export DOTFILES="/home/daniel/data/meus-repositorios/dotfiles"
export FACULDADE="/home/daniel/data/faculdade"
export IHC="$FACULDADE/interacao-humano-computador"
export DESAFIOS="$FACULDADE/desafios-de-programacao"
export SISOP_I="$FACULDADE/sistemas-operacionais-I"
export SEMANTICA="$FACULDADE/semantica-formal"
export MLP="$FACULDADE/modelos-de-linguagens-de-programacao"
export ESPECIFICACAO="$FACULDADE/especificacao-formal"
export REDES="$FACULDADE/redes"
export COMPILADORES="$FACULDADE/compiladores"
export SISOP_II="$FACULDADE/sistemas-operacionais-II"
export FTF="$FACULDADE/fundamentos-de-tolerancia-a-falhas"
export HISTORIA="$FACULDADE/historia-da-computacao"
export APRENDIZADO="$FACULDADE/aprendizado-de-maquina"
export VISAO="$FACULDADE/fundamentos-de-visao-computacional"
export PROJETO_BD="$FACULDADE/projeto-de-banco-de-dados"
export HIPERDOCS="$FACULDADE/projeto-de-hiperdocumentos"
export LAMBDA="$FACULDADE/topicos-especiais-em-computacao-xv-lambda"

## Sourcing other files
### Load useful functions
source $DOTFILES/scripts/functions.sh

## Aliases
alias cl="clear"
alias docker="sudo docker"
alias organize-receipts="python3 ${DOTFILES}/scripts/organize-receipts.py"
